# Generated by Django 3.2.8 on 2021-10-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일')),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('auth_number', models.IntegerField(verbose_name='인증 번호')),
                ('password_modified_at', models.DateTimeField(blank=True, null=True, verbose_name='비밀번호 수정일')),
            ],
            options={
                'db_table': 'tb_auth',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일')),
                ('user_index', models.AutoField(primary_key=True, serialize=False, verbose_name='유저고유번호')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='nickname')),
                ('password', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
    ]
